name: 'Hello World by Calvin'
description: 'Testing JS Jobs'

# runs:
#   using: "composite"
#   steps:
#     - run: echo Hello ${{ inputs.who-to-greet }}.
#       shell: bash
#     - id: random-number-generator
#       run: echo "::set-output name=random-number::$(echo $RANDOM)"
#       shell: bash
#     - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
#       shell: bash          
#     - run: goodbye.sh
#       shell: bash

runs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node test.js
        working-directory: ./.github/workflows